app/blog/urls.py
from django.urls import path
from .views import Index, PostView, AddPost, EditPost, DeletePost

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("post/<int:pk>/", PostView.as_view(), name="post"),
    path("add/", AddPost.as_view(), name="add_post"),
    path("edit/<int:pk>", EditPost.as_view(), name="edit_post"),
    path("del/<int:pk>", DeletePost.as_view(), name="delete_post"),
]

app/portfolio/urls.py
from django.urls import path
from .views import index, generic, ProjectDetailView, ProjectListView

urlpatterns = [
    path("", ProjectListView.as_view(), name="portfolio_index"),
    path("generic", generic, name="generic"),
    path("proj/<int:pk>", ProjectDetailView.as_view(), name="portfolio-detail-view"),
]

app/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("prometheus/", include("django_prometheus.urls")),
    path("members/", include("django.contrib.auth.urls")),
    path("members/", include("authentication.urls"), name="auth"),
    path("", include("blog.urls"), name="blog"),
    path("charts/", include("charts.urls"), name="charts"),
    path("portfolio/", include("portfolio.urls"), name="portfolio"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/portfolio/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Portfolio(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to="images/")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("portfolio-detail-view", kwargs={"pk": self.pk})

app/portfolio/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView
from .models import Portfolio


# Create your views here.
def index(request):
    tiles_data = []
    titles = ["Magna", "Lorem"]
    base_image_path = "portfolio/images/pic{:02}.jpg"  # Using string formatting to generate image paths
    description = (
        "Sed nisl arcu euismod sit amet nisi lorem etiam dolor veroeros et feugiat."
    )
    link_url = "generic"

    # Assuming you want to create 12 tiles based on your example
    for i in range(1, 13):
        tile = {
            # "style": "style{}".format(i),
            "title": titles[i % 2],
            "image_url": base_image_path.format(i),
            "description": description,
            "link_url": link_url,
        }
        tiles_data.append(tile)

    return render(request, "portfolio/index.html", {"tiles": tiles_data})


def generic(request):
    return render(request, "portfolio/generic.html")


class ProjectListView(ListView):
    model = Portfolio
    template_name = "portfolio/index.html"


class ProjectDetailView(DetailView):
    model = Portfolio
    template_name = "portfolio/detailview.html"

app/portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Phantom by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title>{% block title %}Phantom by HTML5 UP{% endblock%}</title>
		<link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" >
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		{% block css %}
		<link rel="stylesheet" href="{% static 'portfolio/assets/css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'portfolio/assets/css/noscript.css' %}" /></noscript>
		{% endblock %}
	</head>
	<body class="is-preload">
		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
				{% include "portfolio/partials/header.html" %}

				<!-- Menu -->
				{% include "portfolio/partials/menu.html" %}

				<!-- Main -->
                {% block content %}
				
                {% endblock %}

				<!-- Footer -->
				{% include "portfolio/partials/footer.html" %}

			</div>

		<!-- Scripts -->
		<script src="{% static 'portfolio/assets/js/jquery.min.js' %}"></script>
		<script src="{% static 'portfolio/assets/js/browser.min.js' %}"></script>
		<script src="{% static 'portfolio/assets/js/breakpoints.min.js' %}"></script>
		<script src="{% static 'portfolio/assets/js/util.js' %}"></script>
		<script src="{% static 'portfolio/assets/js/main.js' %}"></script>
		

	</body>
</html>

app/portfolio/templates/portfolio/detailview.html
<!DOCTYPE HTML>
{% extends "portfolio/base.html" %}
{% load static %}
{% block title %}Phantom{% endblock %}
{% block css %}
	<link rel="stylesheet" href="{% static 'portfolio/assets/css/main.css' %}" />
	<noscript><link rel="stylesheet" href="{% static 'portfolio/assets/css/noscript.css' %}" /></noscript>
{% endblock %}
{% block content %}
<div id="main">
	<div class="inner">
		<h1>{{ portfolio.title }}</h1>
		<span class="image main"><img src="{{ portfolio.image.url }}" alt="" /></span>
		<p>{{ portfolio.description }}</p>
	</div>
</div>
{% endblock %}

app/portfolio/templates/portfolio/generic.html
<!DOCTYPE HTML>
{% extends "portfolio/base.html" %}
{% load static %}
{% block title %}Phantom{% endblock %}
{% block css %}
	<link rel="stylesheet" href="{% static 'portfolio/assets/css/main.css' %}" />
	<noscript><link rel="stylesheet" href="{% static 'portfolio/assets/css/noscript.css' %}" /></noscript>
{% endblock %}
{% block content %}
<div id="main">
	<div class="inner">
		<h1>Generic Page</h1>
		<span class="image main"><img src="{% static 'portfolio/images/pic13.jpg' %}" alt="" /></span>
		<p>Donec eget ex magna. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fergiat. Pellentesque in mi eu massa lacinia malesuada et a elit. Donec urna ex, lacinia in purus ac, pretium pulvinar mauris. Curabitur sapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique.</p>
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis dapibus rutrum facilisis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Etiam tristique libero eu nibh porttitor fermentum. Nullam venenatis erat id vehicula viverra. Nunc ultrices eros ut ultricies condimentum. Mauris risus lacus, blandit sit amet venenatis non, bibendum vitae dolor. Nunc lorem mauris, fringilla in aliquam at, euismod in lectus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In non lorem sit amet elit placerat maximus. Pellentesque aliquam maximus risus, vel venenatis mauris vehicula hendrerit.</p>
		<p>Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque venenatis dolor imperdiet dolor mattis sagittis. Praesent rutrum sem diam, vitae egestas enim auctor sit amet. Pellentesque leo mauris, consectetur id ipsum sit amet, fersapien risus, commodo eget turpis at, elementum convallis elit. Pellentesque enim turpis, hendrerit tristique lorem ipsum dolor.</p>
	</div>
</div>
{% endblock %}

app/portfolio/templates/portfolio/index.html
{% extends "portfolio/base.html" %}
{% load static %}
{% block title %}Phantom{% endblock %}
{% block css %}
	<link rel="stylesheet" href="{% static 'portfolio/assets/css/main.css' %}" />
	<noscript><link rel="stylesheet" href="{% static 'portfolio/assets/css/noscript.css' %}" /></noscript>
{% endblock %}
{% block content %}
	<div id="main">
		<div class="inner">
			<header>
				<h1>This is Phantom, a free, fully responsive site<br />
				template designed by <a href="http://html5up.net">HTML5 UP</a>.</h1>
				<p>Etiam quis viverra lorem, in semper lorem. Sed nisl arcu euismod sit amet nisi euismod sed cursus arcu elementum ipsum arcu vivamus quis venenatis orci lorem ipsum et magna feugiat veroeros aliquam. Lorem ipsum dolor sit amet nullam dolore.</p>
			</header>
			<section class="tiles">
				{% for tile in portfolio_list %}
                    <article class=""> <!-- Consider dynamically assigning the style class if needed -->
                        <span class="image">
                            <img src="{{ tile.image.url }}" alt="Picture" />
                        </span>
                        <a href="{% url 'portfolio-detail-view' tile.pk %}">
                            <h2>{{ tile.title }}</h2>
                            <div class="content">
                                <p>{{ tile.description }}</p>
                            </div>
                        </a>
                    </article>
                {% endfor %}
			</section>
		</div>
	</div>
{% endblock %}